name: CICD

on:
  workflow_dispatch:
   inputs:
    environement:
      description: This is the environement where this flow runs
      default: 'dev'
      required: true
      type: choice
      options:
        - dev
        - prod
        - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Code clone from github"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Build"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "App Deployed"
