# This is workflow Names
name: Hello Workflow

on: 
  push:
    branches: [main]
    paths:
      - '**.html'
      - '**.yml'
# This are jobs inside workflow
jobs:
  # Name Of Job
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to Users
        run: echo "Hello Dosto"

      - name: Say Hello to User Name
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python,docker,etc.
        run: docker --version && python --version
        
  
