name: Portfolio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set-up github pages
      uses: actions/configure-pages@v4

    - name: Upload static files
      uses: actions/upload-pages-artifact@v4
      with:
        path: '.'

    - name: Deploy to github pages
      uses: actions/deploy-pages@v4
    
    
